# example values

indexing-settings:
  sites:
    - url: https://www.bequiet.com/ru
      name: bequiet.com
    - url: https://www.lenta.ru
      name: Лента.ру
      millis: 100
    - url: https://www.skillbox.ru
      name: Skillbox
      millis: 100
    - url: https://www.playback.ru
      name: PlayBack.Ru
      millis: 100

jsoup-settings:
  user-agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:25.0) Gecko/20100101 Firefox/25.0
  reffer: http://www.google.com
  socket-timeout: 30000

server:
  port: 8080

spring:
  datasource:
    username: user
    password: pass
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requir
      eSSL=false&allowPublicKeyRetrieval=true
    separator: ^;
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
#    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always